//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 03:01:29 AM BRT 
//


package br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.EntityType;
import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.PropertiesGroup;
import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.PropertyBooleanType;
import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.PropertyCalendarType;
import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.PropertyEntityType;
import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.PropertyNumericType;
import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.PropertyStringType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Entity_QNAME = new QName("http://orionsoft.net.br/entityMetadata", "entity");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link PropertyNumericType }
     * 
     */
    public PropertyNumericType createPropertyNumericType() {
        return new PropertyNumericType();
    }

    /**
     * Create an instance of {@link PropertyEntityType }
     * 
     */
    public PropertyEntityType createPropertyEntityType() {
        return new PropertyEntityType();
    }

    /**
     * Create an instance of {@link PropertyBooleanType }
     * 
     */
    public PropertyBooleanType createPropertyBooleanType() {
        return new PropertyBooleanType();
    }

    /**
     * Create an instance of {@link PropertyStringType }
     * 
     */
    public PropertyStringType createPropertyStringType() {
        return new PropertyStringType();
    }

    /**
     * Create an instance of {@link PropertiesGroup }
     * 
     */
    public PropertiesGroup createPropertiesGroup() {
        return new PropertiesGroup();
    }

    /**
     * Create an instance of {@link PropertyCalendarType }
     * 
     */
    public PropertyCalendarType createPropertyCalendarType() {
        return new PropertyCalendarType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orionsoft.net.br/entityMetadata", name = "entity")
    public JAXBElement<EntityType> createEntity(EntityType value) {
        return new JAXBElement<EntityType>(_Entity_QNAME, EntityType.class, null, value);
    }

}
