//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 03:01:29 AM BRT 
//


package br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.PropertyType;


/**
 * <p>Java class for PropertyEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyEntityType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://orionsoft.net.br/entityMetadata}PropertyType">
 *       &lt;attribute name="editShowEmbedded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="editShowList" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="allowSubQuery" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyEntityType")
public class PropertyEntityType
    extends PropertyType
{

    @XmlAttribute(name = "editShowEmbedded")
    protected Boolean editShowEmbedded;
    @XmlAttribute(name = "editShowList")
    protected Boolean editShowList;
    @XmlAttribute(name = "allowSubQuery")
    protected Boolean allowSubQuery;
    @XmlAttribute(name = "overrideType")
    protected String overrideType;

    /**
     * Gets the value of the editShowEmbedded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEditShowEmbedded() {
        if (editShowEmbedded == null) {
            return false;
        } else {
            return editShowEmbedded;
        }
    }

    /**
     * Sets the value of the editShowEmbedded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditShowEmbedded(Boolean value) {
        this.editShowEmbedded = value;
    }

    /**
     * Gets the value of the editShowList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEditShowList() {
        if (editShowList == null) {
            return false;
        } else {
            return editShowList;
        }
    }

    /**
     * Sets the value of the editShowList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditShowList(Boolean value) {
        this.editShowList = value;
    }

    /**
     * Gets the value of the allowSubQuery property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowSubQuery() {
        if (allowSubQuery == null) {
            return false;
        } else {
            return allowSubQuery;
        }
    }

    /**
     * Sets the value of the allowSubQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowSubQuery(Boolean value) {
        this.allowSubQuery = value;
    }

    /**
     * Gets the value of the overrideType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverrideType() {
    	return overrideType;
    }

    /**
     * Sets the value of the overrideType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverrideType(String value) {
        this.overrideType = value;
    }

}
