//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 03:01:29 AM BRT 
//

package br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates.PropertyType;

/**
 * <p>
 * Java class for PropertyStringType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyStringType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://orionsoft.net.br/entityMetadata}PropertyType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyStringType")
public class PropertyStringType extends PropertyType {

	@XmlAttribute(name = "html")
	protected Boolean html;

	public boolean isHtml() {
		if (html == null) {
			return true;
		} else {
			return html;
		}
	}

	public void setHtml(Boolean html) {
		this.html = html;
	}

}
