//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 03:01:29 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://orionsoft.net.br/entityMetadata", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.orionsoft.monstrengo.crud.entity.metadata.xml.templates;
